"""受支持文档格式与 reader 选择的稳定入口。"""

from .registry import (
    DOCLING_ENGINE,
    ENGINE_ENV_VAR,
    NATIVE_ENGINE,
    DocumentReader,
    LegacyOfficeBridge,
    UnsupportedDocumentFormat,
    UnsupportedLegacyOfficeFormat,
    configured_engine,
    configured_legacy_office_bridge,
    configured_processor_fingerprint,
    docling_available,
    get_reader,
    read_docx,
    read_document,
    read_image,
    read_pdf,
    read_plain_text,
    read_pptx,
    read_with_docling,
    supported_suffixes,
    validate_image_payload,
)

__all__ = [
    "DOCLING_ENGINE",
    "ENGINE_ENV_VAR",
    "NATIVE_ENGINE",
    "DocumentReader",
    "LegacyOfficeBridge",
    "UnsupportedDocumentFormat",
    "UnsupportedLegacyOfficeFormat",
    "configured_engine",
    "configured_legacy_office_bridge",
    "configured_processor_fingerprint",
    "docling_available",
    "get_reader",
    "read_docx",
    "read_document",
    "read_image",
    "read_pdf",
    "read_plain_text",
    "read_pptx",
    "read_with_docling",
    "supported_suffixes",
    "validate_image_payload",
]
