"""视觉源到有界像素载荷的纯准备能力。"""

from .payload import (
    EXPANDED_REGION_FACTOR,
    MAX_RENDER_SCALE,
    MAX_SOURCE_BYTES,
    MAX_SOURCE_PIXELS,
    MIN_REGION_MARGIN_PT,
    MIN_RENDER_SCALE,
    PDF_SUFFIX,
    PREPARED_VISUAL_ARTIFACT_RECEIPT_CONTRACT,
    PREPARED_VISUAL_RENDER_RECIPE_CONTRACT,
    REGION_MARGIN_RATIO,
    PayloadFailure,
    PayloadRefusal,
    PreparedVisualArtifactBundle,
    PreparedVisualArtifactReceipt,
    VisionPayload,
    build_prepared_visual_artifact_receipt,
    prepare_payload,
    prepare_payload_with_receipt,
    validate_prepared_visual_artifact_receipt,
)

__all__ = [
    "EXPANDED_REGION_FACTOR",
    "MAX_RENDER_SCALE",
    "MAX_SOURCE_BYTES",
    "MAX_SOURCE_PIXELS",
    "MIN_REGION_MARGIN_PT",
    "MIN_RENDER_SCALE",
    "PDF_SUFFIX",
    "PREPARED_VISUAL_ARTIFACT_RECEIPT_CONTRACT",
    "PREPARED_VISUAL_RENDER_RECIPE_CONTRACT",
    "REGION_MARGIN_RATIO",
    "PayloadFailure",
    "PayloadRefusal",
    "PreparedVisualArtifactBundle",
    "PreparedVisualArtifactReceipt",
    "VisionPayload",
    "build_prepared_visual_artifact_receipt",
    "prepare_payload",
    "prepare_payload_with_receipt",
    "validate_prepared_visual_artifact_receipt",
]
