"""Workspace 持久 Document 权威的窄应用 facade。"""

from .admission import (
    CHUNKER_FINGERPRINT,
    DocumentStorePort,
    chunk_text,
    has_reusable_content_artifact,
    ingest,
    ingest_document_path,
    ingest_prepared_in_transaction,
    reuse_content_artifact_in_transaction,
)
from .catalog import edit, get_document, list_document_versions, list_documents, remove
from .contracts import (
    DOCUMENT_CHUNK_CONTRACT_VERSION,
    CurrentDocumentPageAuthority,
    CurrentDocumentResourceChunk,
    CurrentDocumentResourceSnapshot,
    DocumentChunkPageBinding,
    DocumentIngestCommitReceipt,
    MountedDocumentIndexBinding,
    MountedDocumentIndexBindingSnapshot,
)
from .mounting import (
    check_mounted_document_freshness,
    detach,
    get_mounted_document_index_binding_snapshot,
    get_retrieval_snapshot,
    is_mounted,
    mount_document,
    is_mounted_in_connection,
    mounted_docs,
    preflight_documents,
    preflight_mounted_documents,
)
from .reading import (
    CurrentFileChunk,
    CurrentFileDocument,
    doc_read,
    get_current_document_chunk,
    get_current_chunk_document,
    get_current_file_document,
    get_current_document_file,
    read_current_file_chunk,
    get_current_document_page_authority,
    get_current_typed_document_chunk,
    get_mounted_current_document_resource_snapshot,
    list_current_document_chunks,
)

__all__ = [
    "CurrentFileChunk",
    "CurrentFileDocument",
    "get_current_file_document",
    "get_current_document_file",
    "get_current_chunk_document",
    "read_current_file_chunk",
    "CHUNKER_FINGERPRINT",
    "DOCUMENT_CHUNK_CONTRACT_VERSION",
    "CurrentDocumentPageAuthority",
    "CurrentDocumentResourceChunk",
    "CurrentDocumentResourceSnapshot",
    "DocumentChunkPageBinding",
    "DocumentIngestCommitReceipt",
    "DocumentStorePort",
    "MountedDocumentIndexBinding",
    "MountedDocumentIndexBindingSnapshot",
    "check_mounted_document_freshness",
    "chunk_text",
    "detach",
    "doc_read",
    "edit",
    "get_current_document_chunk",
    "get_current_document_page_authority",
    "get_current_typed_document_chunk",
    "get_document",
    "get_mounted_current_document_resource_snapshot",
    "get_mounted_document_index_binding_snapshot",
    "get_retrieval_snapshot",
    "has_reusable_content_artifact",
    "ingest",
    "ingest_document_path",
    "ingest_prepared_in_transaction",
    "is_mounted",
    "mount_document",
    "is_mounted_in_connection",
    "list_current_document_chunks",
    "list_document_versions",
    "list_documents",
    "mounted_docs",
    "preflight_documents",
    "preflight_mounted_documents",
    "remove",
    "reuse_content_artifact_in_transaction",
]
